### ISSUE TITLE
Add #twice for InstrumentMatcher

### ISSUE THREAD

**Issue by lmansur** [vvlad/rspec-instrumentation-matcher#5]
@vvlad thank you for the gem! It makes my specs a lot cleaner.

I have a situation where I have to test if an instrumentation happened twice. Since the gem has a `#once` method, I expected it to also have a `#twice`, as RSpec does. Unfortunately, it doesn't have it.

Looking at the implementation of `#once` I feel like the implementation of `#twice` would be extremely simple.

If you think this would be a valid addition to the gem, I'm happy to create a PR with the implementation for your review.

Thanks!

**Comment by vvlad** [comment]
@lmansur I'm glad to hear that this gem helps you keep your code clean.

Regarding the `#twice` I don't see any reason why not to have it. Go ahead with the PR.
Ty.

**Comment by lmansur** [comment]
Thanks, @vvlad
